name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: modules
          soft_fail: true

  checkov:
    name: Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: modules
          framework: terraform
          quiet: true
          soft_fail: false
          config_file: .checkov.yaml
